### ISSUE TITLE
Needless escapes in Markdown since 2.1.1

### ISSUE THREAD

**Issue by kawanet** [syntax-tree/mdast-util-to-markdown#66] opened 2024-11-21 09:48 UTC
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=Issues) and couldn’t find anything (or linked relevant results below)

### Affected packages and versions

mdast-util-to-markdown

### Steps to reproduce

```js
import {fromMarkdown} from 'mdast-util-from-markdown'
import {toMarkdown} from 'mdast-util-to-markdown'
import {toHast} from 'mdast-util-to-hast'
import {toHtml} from 'hast-util-to-html'

const md = `foo***bar***buz`;
console.log(md) // original
console.log(toMarkdown(fromMarkdown(md))) // round trip
console.log(toHtml(toHast(fromMarkdown(md)))) // HTML
```

### Expected behavior

until mdast-util-to-markdown version 2.1.0, or commit df0d6a6, it works correctly.
`toMarkdown(fromMarkdown(md))` runs the round trip from Markdown to Markdown.

```
foo***bar***buz
foo***bar***buz
<p>foo<em><strong>bar</strong></em>buz</p>
```

### Actual behavior

since mdast-util-to-markdown version 2.1.1, or commit 97fb8181, it made characters escaped needlessly just before and after both `*` and `**`.
`toMarkdown(fromMarkdown(md))` **cannot** run the round trip from Markdown to Markdown.
`toHtml(toHast(fromMarkdown(md)))` still has no trouble on the other hand.

```
foo***bar***buz
fo&#x6F;***bar***&#x62;uz
<p>foo<em><strong>bar</strong></em>buz</p>
```

It means version 2.1.1 has a breaking change. Version 2.1.2 has the same issue.
Thank you maintaining this anyway.

### Affected runtime and version

node@22.11.0

**Comment by wooorm** [comment] 2024-11-21 09:53
Hi! This looks like a duplicate of #65!

**Closed by wooorm** 2024-11-21 09:53 UTC
Labels: 🤞 phase/open

**Comment by kawanet** [comment] 2024-11-21 11:08
Thank you for pointing me to the related issue.
My actual production app is to generate Markdown from mdast object without parsing Markdown.
I'll then try to update the app to add leading/trailing spaces around `strong` nodes to avoid the needless escaping.

The commit 97fb818 might be able to give the new minor version number `2.2.0` with the breaking change, by the way.

- 1.5.0 - `fo&#x6F;***bar***&#x62;uz`  
- 2.0.0 - `foo***bar***buz` 😍 
- 2.1.0 - `foo***bar***buz` 😍 
- 2.1.1 - `fo&#x6F;***bar***&#x62;uz` 😢 
- 2.1.2 - `fo&#x6F;***bar***&#x62;uz` 😢

**Comment by wooorm** [comment] 2024-11-21 11:59
It depends on what you do, what I’d recommend. If you can generate spaces, I would indeed strongly recommend them.

Note that I do not consider escaping things a breaking change; that markdown still renders the same, and the HTML output is still the same. That wasn’t the case before. That escape is not needed in *some* cases. But it is needed in other cases. This patch fixes actual bugs!
